ingressroute:
  enabled: false
  overrideHost: ""
  routes:
    - path: /
      host: chat.[a-z0-9.]+
      priority: 900
      serviceName: open-webui
      servicePort: 80

open-webui:

  ollama:
    gpu:
      enabled: false
      type: 'nvidia'
      number: 1
    models:
      pull: []
      run: []

  sso:
    enabled: false
    enableSignup: true

    google:
      enabled: false
      clientId: ""
      clientSecret: ""

    oidc:
      enabled: false
      clientId: ""
      clientSecret: ""
      providerUrl: ""
      providerName: "SSO"
      scopes: "openid email profile"

  # https://docs.openwebui.com/getting-started/env-configuration
  extraEnvVars:
    - name: OPENID_PROVIDER_URL
      value: "https://accounts.google.com/.well-known/openid-configuration"
    - name: ENABLE_SIGNUP
      value: "False"
    - name: DEFAULT_USER_ROLE
      value: "user"
    - name: ENABLE_PERSISTENT_CONFIG
      value: "false"
